Repository ClimateImpactLab/dodola, pull requests merged in 2021-12, with the labels that each got.

#146 Update biascorrection validation
  HISTORY.rst
  dodola/core.py
Labels: bug

#145 add dtr correction for small dtr values
  HISTORY.rst
  dodola/cli.py
  dodola/core.py
  dodola/services.py
  dodola/tests/test_services.py
Labels: enhancement

#144 360 days calendar support
  dodola/core.py
  dodola/tests/test_core.py
Labels: enhancement

#143 precip units temporary replacement
  HISTORY.rst
  dodola/core.py
  dodola/services.py
  dodola/tests/test_core.py
Labels: bug

#151 Fix 360 day calendar conversion chunk errors from dodola.services.clean_cmip6
  HISTORY.rst
  dodola/core.py
  dodola/services.py
Labels: bug

#152 Remove cruft code, dependencies
  HISTORY.rst
  dodola/cli.py
  dodola/core.py
  dodola/services.py
  dodola/tests/test_cli.py
  dodola/tests/test_services.py
  environment.yaml
Labels: enhancement

#153 update DTR validation ranges
  HISTORY.rst
  dodola/core.py
Labels: bug

#156 Internal: Add Makefile, use for CI workflow
  .github/workflows/test.yaml
  Makefile
Labels: enhancement

#157 Internal: Add PR template for GH
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#163 floor and ceiling for DTR
  CHANGELOG.md
  dodola/cli.py
  dodola/core.py
  dodola/services.py
  dodola/tests/test_services.py
Labels: enhancement

#166 corrected DTR ceiling boolean expression and tests accordingly
  dodola/core.py
  dodola/tests/test_services.py
Labels: bug
