Repository ClimateImpactLab/dodola, pull requests merged in 2021-06, with the labels that each got.

#78 add wet day frequency correction
  HISTORY.rst
  dodola/cli.py
  dodola/core.py
  dodola/services.py
  dodola/tests/test_cli.py
  dodola/tests/test_services.py
Labels: enhancement

#90 Add dask-kubernetes, distributed, and better subprocess handling in container
  Dockerfile
  HISTORY.rst
  environment.yaml
Labels: bug, enhancement

#88 Fix bug in dodola.services.train_quantiledeltamapping() accounting for endpoints
  HISTORY.rst
  dodola/core.py
  dodola/tests/test_core.py
Labels: bug
