Repository ClimateImpactLab/dodola, pull requests merged in 2021-04, with the labels that each got.

#47 Add naive log hushing
  dodola/cli.py
Labels: enhancement

#54 Fix bad ffspec, adlfs imports
  environment.yaml
Labels: bug

#52 Cast CLI option to int, fix rechunker maxmem error
  dodola/cli.py
Labels: bug

#39 update regridding output dimensions
  dodola/cli.py
  dodola/core.py
  dodola/services.py
  dodola/tests/test_services.py
Labels: bug, enhancement

#42 add new leapday removal service and cmip6 cleanup service
  dodola/cli.py
  dodola/core.py
  dodola/services.py
  dodola/tests/test_services.py
Labels: enhancement

#59 fix bug
  dodola/core.py
Labels: bug

#60 Use simple xarray rechunking
  HISTORY.rst
  dodola/cli.py
  dodola/repository.py
  dodola/services.py
  dodola/tests/test_services.py
  environment.yaml
Labels: bug

#61 Require fsspec URLs, refactor
  HISTORY.rst
  dodola/cli.py
  dodola/repository.py
  dodola/services.py
  dodola/tests/test_repository.py
  dodola/tests/test_services.py
  environment.yaml
Labels: enhancement

#63 Fix TypeError in dodola.cli.py::rechunk
  HISTORY.rst
  dodola/cli.py
Labels: bug

#67 add domain file functionality to buildweights
  HISTORY.rst
  dodola/cli.py
  dodola/core.py
  dodola/services.py
  dodola/tests/test_services.py
Labels: enhancement

#65 Add downscaling service
  HISTORY.rst
  dodola/cli.py
  dodola/core.py
  dodola/services.py
  dodola/tests/test_services.py
  environment.yaml
Labels: enhancement
