Repository ClimateImpactLab/dodola, pull requests merged in 2021-03, with the labels that each got.

#24 Add rechunker service, refactor repository.py to simplify
  Dockerfile
  dodola/cli.py
  dodola/core.py
  dodola/repository.py
  dodola/services.py
  dodola/tests/test_cli.py
  dodola/tests/test_repository.py
  dodola/tests/test_services.py
  environment.yaml
Labels: enhancement

#25 Add decorator-based service logging, clean CLI storage authentication
  dodola/cli.py
  dodola/services.py
Labels: documentation, enhancement

#26 CI/CD push containers on release
  .github/workflows/buildpushrelease.yaml
Labels: enhancement

#31 Fix exception catching in logging decorator
  dodola/services.py
Labels: bug

#29 Add service for regridding zarrs
  dodola/cli.py
  dodola/core.py
  dodola/services.py
  dodola/tests/test_cli.py
  dodola/tests/test_services.py
Labels: enhancement

#33 fix buildweights bug
  dodola/cli.py
Labels: bug

#35 fix cli bug
  dodola/cli.py
Labels: bug

#37 fix cli bug
  dodola/cli.py
Labels: bug
