Repository ClimateImpactLab/dodola, pull requests merged in 2021-11, with the labels that each got.

#119 update xclim version after merging in newest xclim changes
  HISTORY.rst
  dodola/core.py
  dodola/tests/test_core.py
  dodola/tests/test_services.py
  environment.yaml
Labels: enhancement

#123 Add pre-training slicing options to train-qdm and train-aiqpd
  HISTORY.rst
  dodola/cli.py
  dodola/core.py
  dodola/services.py
  dodola/tests/test_core.py
  dodola/tests/test_services.py
Labels: enhancement

#124 Quick fix validation reading entire zarr store for QC check
  HISTORY.rst
  dodola/core.py
Labels: bug

#128 Fix ValueError from chunks in time in existing workflows
  HISTORY.rst
  dodola/services.py
Labels: bug

#129 Add QDM output Zarr priming, region writing, metadata, multi-year processing
  HISTORY.rst
  dodola/cli.py
  dodola/core.py
  dodola/repository.py
  dodola/services.py
  dodola/tests/test_cli.py
  dodola/tests/test_services.py
Labels: enhancement

#130 Add AIQPD output Zarr priming, slicing, region writing, metadata, multi-year processing
  HISTORY.rst
  dodola/cli.py
  dodola/core.py
  dodola/services.py
  dodola/tests/test_cli.py
  dodola/tests/test_services.py
Labels: enhancement

#131 Refactor AIQPD references to QPLAD in all things
  HISTORY.rst
  dodola/cli.py
  dodola/core.py
  dodola/services.py
  dodola/tests/test_cli.py
  dodola/tests/test_services.py
Labels: documentation

#132 Upgrade Docker base image to continuumio/miniconda3:4.10.3
  Dockerfile
  HISTORY.rst
Labels: enhancement

#133 Add `dodola get-attrs` command
  HISTORY.rst
  dodola/cli.py
  dodola/services.py
  dodola/tests/test_cli.py
  dodola/tests/test_services.py
Labels: enhancement

#134 Add qdm, qplad option to set root attrs from json
  HISTORY.rst
  dodola/cli.py
  dodola/repository.py
  dodola/services.py
  dodola/tests/test_repository.py
Labels: enhancement

#135 Fix attrs missing from services.apply_qplad output Datasets
  HISTORY.rst
  dodola/core.py
Labels: bug

#136 Add additional integration tests for dodola.core.*_analogdownscaling functions
  HISTORY.rst
  dodola/tests/test_core.py
Labels: enhancement

#137 update xclim analog downscaling method name and version
  dodola/core.py
  environment.yaml
Labels: documentation, enhancement

#140 distinguish missing from excess timesteps in timesteps validation
  HISTORY.rst
  dodola/core.py
Labels: bug

#141 click wetday correction
  HISTORY.rst
  dodola/cli.py
  dodola/services.py
Labels: enhancement
