Repository ClimateImpactLab/dodola, pull requests merged in 2021-07, with the labels that each got.

#92 Add astype arg to regrid(s)
  HISTORY.rst
  dodola/cli.py
  dodola/core.py
  dodola/services.py
  dodola/tests/test_services.py
Labels: enhancement

#95 Add analogdownscaling qdm options
  HISTORY.rst
  dodola/cli.py
  dodola/core.py
  dodola/services.py
  dodola/tests/test_core.py
  environment.yaml
Labels: enhancement

#94 Add precip unit conversion
  HISTORY.rst
  dodola/core.py
  dodola/tests/test_services.py
Labels: enhancement

#104 Fix application logging to stdout
  HISTORY.rst
  dodola/cli.py
Labels: bug

#105 Bump xclim to v0.28.0, improve environment notes
  HISTORY.rst
  environment.yaml
Labels: documentation, enhancement

#106 Add papermill, intake-esm to docker environment
  HISTORY.rst
  environment.yaml
Labels: enhancement

#108 Add --cyclic option to regrid cli and services
  HISTORY.rst
  dodola/cli.py
  dodola/core.py
  dodola/services.py
  dodola/tests/test_core.py
Labels: bug, enhancement
