Repository ClimateImpactLab/dodola, pull requests merged in 2022-01, with the labels that each got.

#168 Remove excess unit conversion info logging
  CHANGELOG.md
  dodola/core.py
  dodola/services.py
Labels: enhancement

#169 Begin to fill-out README.md
  CHANGELOG.md
  README.md
Labels: documentation

#170 extend minimum temperature tolerance from 150 K to 130 K
  CHANGELOG.md
  dodola/core.py
Labels: enhancement

#176 include dtype in np.random.uniform addressing #175
  CHANGELOG.md
  dodola/core.py
Labels: bug
